services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: alllbe-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alllbe_dev
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # Neon Proxy - ローカルPostgreSQLをNeon互換にする
  neon-proxy:
    image: ghcr.io/timowilhelm/local-neon-http-proxy:main
    container_name: alllbe-neon-proxy
    environment:
      PG_CONNECTION_STRING: "postgres://postgres:postgres@postgres:5432/alllbe_dev"
    ports:
      - "4444:4444"
    depends_on:
      postgres:
        condition: service_healthy

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.22.4
    container_name: alllbe-temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
    ports:
      - "7233:7233" # gRPC
      - "8233:8233" # HTTP API
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "tctl", "--address", "temporal:7233", "cluster", "health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal UI (Optional - for debugging)
  temporal-ui:
    image: temporalio/ui:2.21.3
    container_name: alllbe-temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - temporal
